### ISSUE TITLE
Undefined identifier long64

### ISSUE THREAD

**Issue by alexhairyman** [D-Programming-Deimos/libX11#6] opened 2012-03-29 00:43 UTC
I am on 32-bit ubuntu 11.04 and libX11 refuses to build at xlibint.d it says undefined identifier long64. I am using a completely vanilla version of dmd 2.058

**Comment by CyberShadow** [comment] 2016-03-29 08:01
`long64` does not occur in `Xlibint.d`, perhaps you meant `LONG64`? Please post the exact error message.

I'm going to close this since it's been 4 years and I'm guessing the problem is no longer relevant or reproducible, but let me know if this should be reopened.

**Closed by CyberShadow** 2016-03-29 08:01 UTC
